# Generated by Django 4.0.5 on 2022-11-12 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0034_product_featured_products_product_is_hot_and_more'),
        ('store', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
