# Generated by Django 4.0.5 on 2022-11-18 15:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cart_product_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=9, null=True),
        ),
    ]
