# Generated by Django 4.0.5 on 2022-11-19 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
