# Generated by Django 4.0.5 on 2022-08-26 19:55

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('dni', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Dni')),
                ('date_of_birth', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('nrc', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='NRC')),
                ('nit', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='NIT')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('opening_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Teléfono fijo')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Celular')),
                ('website', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Website')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/%Y/%m/%d', verbose_name='Imagen')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañías',
                'ordering': ['id'],
                'permissions': {('change_company', 'Can change company')},
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('doc_type', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tipo doc.')),
                ('doc_ser', models.CharField(blank=True, max_length=15, null=True, verbose_name='Serie doc.')),
                ('doc_num', models.CharField(blank=True, max_length=15, null=True, verbose_name='Num. doc.')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.company')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código interno')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código barra')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción detallada')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=9, null=True, verbose_name='Costo')),
                ('fact', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Factor')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=9, null=True, verbose_name='Precio venta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock')),
                ('fact2', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Factor 2')),
                ('fact3', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Factor 3')),
                ('price2', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=9, null=True, verbose_name='Precio 2')),
                ('price3', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=9, null=True, verbose_name='Precio 3')),
                ('tags', models.CharField(blank=True, max_length=150, null=True, verbose_name='Palabras clave')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='Ult. fecha compra')),
                ('is_inventoried', models.BooleanField(default=True, verbose_name='¿Es inventariado?')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('doc_num', models.CharField(blank=True, max_length=15, null=True, verbose_name='Num. doc.')),
                ('type', models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo Mov.')),
                ('cant', models.IntegerField(default=0)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.sale')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.sale')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
