# Generated by Django 3.2.7 on 2022-09-04 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='inv.category', verbose_name='Categoría'),
            preserve_default=False,
        ),
    ]
