# Generated by Django 4.0.5 on 2022-10-15 03:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrc', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='NRC')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres')),
                ('surname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos')),
                ('razon_social', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón Social')),
                ('nit', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='NIT')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de nacimiento')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('doc_type', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tipo doc.')),
                ('doc_ser', models.CharField(blank=True, max_length=15, null=True, verbose_name='Serie doc.')),
                ('doc_num', models.CharField(blank=True, max_length=15, null=True, verbose_name='Num. doc.')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.company')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.supplier')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.entry')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.product')),
            ],
            options={
                'verbose_name': 'Detalle de Entrada',
                'verbose_name_plural': 'Detalle de Entradas',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
