# Generated by Django 4.0.5 on 2022-10-16 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_supplier_entry_detentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movements',
            options={'ordering': ['id'], 'verbose_name': 'Movimiento de Kardex', 'verbose_name_plural': 'Movimientos de Kardex'},
        ),
        migrations.AddField(
            model_name='movements',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.entry'),
        ),
        migrations.AlterField(
            model_name='movements',
            name='prod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.product'),
        ),
        migrations.AlterField(
            model_name='movements',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.sale'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='NIT'),
        ),
    ]
