# Generated by Django 4.0.5 on 2022-10-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_alter_movements_options_movements_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movements',
            name='doc_ser',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Num. doc.'),
        ),
    ]
