# Generated by Django 4.0.5 on 2022-10-17 19:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_movements_doc_ser'),
    ]

    operations = [
        migrations.AddField(
            model_name='movements',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=9, null=True, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='movements',
            name='doc_ser',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Serie doc.'),
        ),
    ]
