# Generated by Django 4.0.5 on 2022-10-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_movements_cost_alter_movements_doc_ser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detentry',
            old_name='price',
            new_name='cost',
        ),
    ]
