# Generated by Django 4.0.5 on 2022-10-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0010_rename_price_detentry_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movements',
            old_name='type',
            new_name='type_mov',
        ),
    ]
