# Generated by Django 4.0.5 on 2022-10-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0014_client_created_at_client_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
