# Generated by Django 4.0.5 on 2022-10-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0018_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
