# Generated by Django 4.0.5 on 2022-10-21 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0022_rename_proper_name_product_root_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='root_name',
        ),
        migrations.AddField(
            model_name='product',
            name='order_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de ordenamiento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.brand', verbose_name='Marca'),
        ),
    ]
