# Generated by Django 4.0.5 on 2022-10-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0025_alter_product_options_alter_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
    ]
