# Generated by Django 4.0.5 on 2022-10-28 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0027_alter_brand_name_alter_brand_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='surname',
        ),
    ]
