# Generated by Django 4.0.5 on 2022-11-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0033_remove_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_products',
            field=models.BooleanField(default=False, verbose_name='Destacados'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='Hot'),
        ),
        migrations.AddField(
            model_name='product',
            name='special_offers',
            field=models.BooleanField(default=False, verbose_name='Ofertas'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalogue',
            field=models.BooleanField(default=True, verbose_name='Catálogo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.BooleanField(default=False, verbose_name='webstore'),
        ),
    ]
