# Generated by Django 4.0.5 on 2022-11-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0036_tiposdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposdoc',
            name='last_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tiposdoc',
            name='last_number',
            field=models.CharField(default=123, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiposdoc',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
