# Generated by Django 4.0.5 on 2022-11-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0037_tiposdoc_last_date_tiposdoc_last_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposdoc',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
