# Generated by Django 4.0.5 on 2022-12-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0040_product_nulled_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nulled_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
