# Generated by Django 4.0.5 on 2022-12-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0041_product_nulled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nulled',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nulled_at',
        ),
        migrations.AddField(
            model_name='entry',
            name='nulled',
            field=models.BooleanField(default=False, verbose_name='Anulado'),
        ),
        migrations.AddField(
            model_name='entry',
            name='nulled_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='nulled',
            field=models.BooleanField(default=False, verbose_name='Anulado'),
        ),
        migrations.AddField(
            model_name='sale',
            name='nulled_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
