# Generated by Django 4.0.5 on 2022-12-02 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0042_remove_product_nulled_remove_product_nulled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
