# Generated by Django 4.0.5 on 2022-12-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0043_alter_entry_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='nulled_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
