# Generated by Django 4.0.5 on 2022-12-04 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0045_alter_entry_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='supplier',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='inv.supplier'),
            preserve_default=False,
        ),
    ]
