# Generated by Django 4.0.5 on 2022-12-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0046_alter_entry_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='supplier_doc_num',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Num. doc. Proveedor'),
        ),
    ]
