# Generated by Django 4.0.5 on 2022-12-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0047_entry_supplier_doc_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
