# Generated by Django 4.0.5 on 2022-12-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0048_group_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
    ]
