# Generated by Django 4.0.5 on 2023-01-20 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0052_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='branch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inv.branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Teléfono'),
        ),
    ]
