# Generated by Django 4.0.5 on 2023-01-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0053_entry_branch_alter_branch_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.branch'),
        ),
    ]
