# Generated by Django 4.0.5 on 2023-01-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0054_alter_entry_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposdoc',
            name='type',
            field=models.CharField(default='E', max_length=1),
            preserve_default=False,
        ),
    ]
