# Generated by Django 4.0.5 on 2023-01-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0055_tiposdoc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='doc_type',
        ),
        migrations.AddField(
            model_name='entry',
            name='doc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inv.tiposdoc'),
            preserve_default=False,
        ),
    ]
