# Generated by Django 4.0.5 on 2023-01-24 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0056_remove_entry_doc_type_entry_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='doc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inv.tiposdoc'),
        ),
    ]
