# Generated by Django 4.0.5 on 2023-01-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0059_alter_entry_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiposdoc',
            old_name='type',
            new_name='movtype',
        ),
    ]
