# Generated by Django 4.0.5 on 2023-01-31 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0061_movements_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inv.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.supplier'),
        ),
    ]
