# Generated by Django 4.0.5 on 2023-02-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0062_alter_entry_company_alter_entry_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposdoc',
            name='last_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
