# Generated by Django 4.0.5 on 2023-02-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_managers_user_is_admin_user_is_superadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
